var React = require('react-native');
var { StyleSheet,} = React;

module.exports = StyleSheet.create(
{
  container: {
    marginTop: 30,
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    textAlignVertical: 'top',
  },
  scroll: {
    width:'90%',
    alignSelf: 'center',
    alignContent: 'center',
    height: 500,
  },
  enterText: {
    marginTop: 50,
    textAlign: 'center',
    fontSize: 50,
    fontWeight: 'bold',
    color: 'red',
  },
  enterTextInfo: {
    fontSize: 15,
    fontWeight: 'normal',
    color: 'grey',
    marginTop: 30,
    marginBottom: 15,
    textAlign: 'center',
  },
  header: {
    flexDirection: 'row',
    backgroundColor: 'red',
    width: '100%',
    height: 50,
  },
  topText: {
    color: '#ccc',
    fontWeight: 'bold',
    textAlign: 'left',
    fontSize: 16,
    marginLeft: 10,
    marginTop: 15,
  },
  topTextUser: {
    color: '#ccc',
    fontWeight: 'bold',
    fontSize: 16,
    marginLeft: 'auto',
    marginRight: 10,
    marginTop: 15,
  },
  logInView:
  {
    flex: 1,
    height: 150,
    width:'100%',
    marginTop: 15,
    height: 150,
  },
  input: {
    marginTop: 10,
    marginBottom: 5,
    alignItems: 'stretch',
    borderColor: '#ccc',
    borderBottomWidth:1,
    height: 25,
    fontSize:20,
    color: 'black',
  },
  loginBtn: {
    alignSelf: 'center',
    marginTop: 15,
    width: '75%',
    backgroundColor: 'red',
    height: 40,
    borderRadius: 5,
  },
  logInBtnText:{
    fontSize: 16,
    fontWeight: 'bold',
    color: 'white',
    marginTop: 10,
    textAlign: 'center',
  },
  lists: {
    height: 50,
    borderColor:'#ccc',
    borderWidth: 1,
    marginTop: 20,
    // textAlignVertical: 'center',
  },
  listTitle:{
    color: '#aaa',
    fontWeight: 'bold',
    textAlign: 'left',
    marginLeft: 10,
    marginTop: 15,
  },
  userIcon:{
     width: 25,
     height: 25,
     marginTop: 10,
     marginRight: 10,
  },
  newsInfo: {
    fontSize: 15,
    fontWeight: 'normal',
    color: 'grey',
    marginTop: 30,
    marginBottom: 20,
    textAlign: 'left',
    marginLeft: 10,
    marginRight: 30,
  },
  buttonToList:{
    color: '#ccc',
    fontWeight: 'bold',
    textAlign: 'left',
    marginLeft: 10,
    marginTop: 0,
    fontSize: 33,
  },
  newsBtnsView:{
    flexDirection: 'row',
    marginTop: 'auto',
    height: 50,
  },
  backBtn:{
    color: '#fff',
    borderColor: 'red',
    borderTopWidth: 1,
    height: 50,
  },
  logOutBtn:{
    backgroundColor: '#f00',
    height: 50,
  },
  backBtnText:{
    fontSize: 20,
    fontWeight: 'bold',
    color: 'red',
    marginTop: 13,
    textAlign: 'center',
  },
  logOutBtnText:{
    fontSize: 20,
    fontWeight: 'bold',
    color: 'white',
    marginTop: 13,
    textAlign: 'center',
  },
});
